"""Added cascade delete to Favorito

Revision ID: 8cfc972a0a44
Revises: 7683cc02fb22
Create Date: 2024-06-01 08:36:31.397020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfc972a0a44'
down_revision = '7683cc02fb22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.drop_constraint('favorito_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorito_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
